### ISSUE TITLE
Question difference with SB

### ISSUE THREAD

**Issue by TParcollet** [magnumresearchgroup/Fastaudio#1]
Hi there !

I wish to use FastAudio in a project involving SpeechBrain. What exactly has changed in the code w.r.t to SB ? From what I see, it basically just is Freeze = False from the standard code, am I right ? It's cool !

**Comment by QuchenFu** [comment]
Hello Dr. Parcollet Titouan,

Sorry for the super late reply:-(
Yes, that is the gist of it, however, apart from parameter change, we do need to register parameters, add cutoff, design sorting, add cuda support, and reformat the matrix for Pytorch calculation. Hope this answers your question.
